# name of the workflow
name: file dependent workflows

on:
    push:
        branches: [main]
        paths:               
          - '**.html'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: say hello to name
            run: echo "$USER"
    
